# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import taranis_pb2 as taranis__pb2


class TaranisStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.getDatabase = channel.unary_unary(
            '/taranis.Taranis/getDatabase',
            request_serializer=taranis__pb2.DatabaseNameModel.SerializeToString,
            response_deserializer=taranis__pb2.DatabaseModel.FromString,
        )
        self.createDatabase = channel.unary_unary(
            '/taranis.Taranis/createDatabase',
            request_serializer=taranis__pb2.NewDatabaseModel.SerializeToString,
            response_deserializer=taranis__pb2.DatabaseModel.FromString,
        )
        self.deleteDatabase = channel.unary_unary(
            '/taranis.Taranis/deleteDatabase',
            request_serializer=taranis__pb2.DatabaseNameModel.SerializeToString,
            response_deserializer=taranis__pb2.Empty.FromString,
        )
        self.getIndex = channel.unary_unary(
            '/taranis.Taranis/getIndex',
            request_serializer=taranis__pb2.IndexQueryModel.SerializeToString,
            response_deserializer=taranis__pb2.IndexModel.FromString,
        )
        self.deleteIndex = channel.unary_unary(
            '/taranis.Taranis/deleteIndex',
            request_serializer=taranis__pb2.IndexQueryModel.SerializeToString,
            response_deserializer=taranis__pb2.Empty.FromString,
        )
        self.createIndex = channel.unary_unary(
            '/taranis.Taranis/createIndex',
            request_serializer=taranis__pb2.NewIndexModel.SerializeToString,
            response_deserializer=taranis__pb2.IndexModel.FromString,
        )
        self.trainIndex = channel.unary_unary(
            '/taranis.Taranis/trainIndex',
            request_serializer=taranis__pb2.IndexQueryModel.SerializeToString,
            response_deserializer=taranis__pb2.Empty.FromString,
        )
        self.reindex = channel.unary_unary(
            '/taranis.Taranis/reindex',
            request_serializer=taranis__pb2.IndexQueryModel.SerializeToString,
            response_deserializer=taranis__pb2.Empty.FromString,
        )
        self.addVectors = channel.unary_unary(
            '/taranis.Taranis/addVectors',
            request_serializer=taranis__pb2.NewVectorsModel.SerializeToString,
            response_deserializer=taranis__pb2.Empty.FromString,
        )
        self.getVectors = channel.unary_unary(
            '/taranis.Taranis/getVectors',
            request_serializer=taranis__pb2.VectorsQueryModel.SerializeToString,
            response_deserializer=taranis__pb2.VectorsReplyModel.FromString,
        )
        self.searchVectors = channel.unary_unary(
            '/taranis.Taranis/searchVectors',
            request_serializer=taranis__pb2.SearchRequestModel.SerializeToString,
            response_deserializer=taranis__pb2.SearchResultListModel.FromString,
        )


class TaranisServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def getDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteDatabase(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIndex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteIndex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createIndex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def trainIndex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reindex(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addVectors(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getVectors(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchVectors(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaranisServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.getDatabase,
            request_deserializer=taranis__pb2.DatabaseNameModel.FromString,
            response_serializer=taranis__pb2.DatabaseModel.SerializeToString,
        ),
        'createDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.createDatabase,
            request_deserializer=taranis__pb2.NewDatabaseModel.FromString,
            response_serializer=taranis__pb2.DatabaseModel.SerializeToString,
        ),
        'deleteDatabase': grpc.unary_unary_rpc_method_handler(
            servicer.deleteDatabase,
            request_deserializer=taranis__pb2.DatabaseNameModel.FromString,
            response_serializer=taranis__pb2.Empty.SerializeToString,
        ),
        'getIndex': grpc.unary_unary_rpc_method_handler(
            servicer.getIndex,
            request_deserializer=taranis__pb2.IndexQueryModel.FromString,
            response_serializer=taranis__pb2.IndexModel.SerializeToString,
        ),
        'deleteIndex': grpc.unary_unary_rpc_method_handler(
            servicer.deleteIndex,
            request_deserializer=taranis__pb2.IndexQueryModel.FromString,
            response_serializer=taranis__pb2.Empty.SerializeToString,
        ),
        'createIndex': grpc.unary_unary_rpc_method_handler(
            servicer.createIndex,
            request_deserializer=taranis__pb2.NewIndexModel.FromString,
            response_serializer=taranis__pb2.IndexModel.SerializeToString,
        ),
        'trainIndex': grpc.unary_unary_rpc_method_handler(
            servicer.trainIndex,
            request_deserializer=taranis__pb2.IndexQueryModel.FromString,
            response_serializer=taranis__pb2.Empty.SerializeToString,
        ),
        'reindex': grpc.unary_unary_rpc_method_handler(
            servicer.reindex,
            request_deserializer=taranis__pb2.IndexQueryModel.FromString,
            response_serializer=taranis__pb2.Empty.SerializeToString,
        ),
        'addVectors': grpc.unary_unary_rpc_method_handler(
            servicer.addVectors,
            request_deserializer=taranis__pb2.NewVectorsModel.FromString,
            response_serializer=taranis__pb2.Empty.SerializeToString,
        ),
        'getVectors': grpc.unary_unary_rpc_method_handler(
            servicer.getVectors,
            request_deserializer=taranis__pb2.VectorsQueryModel.FromString,
            response_serializer=taranis__pb2.VectorsReplyModel.SerializeToString,
        ),
        'searchVectors': grpc.unary_unary_rpc_method_handler(
            servicer.searchVectors,
            request_deserializer=taranis__pb2.SearchRequestModel.FromString,
            response_serializer=taranis__pb2.SearchResultListModel.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'taranis.Taranis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
